version: "3.9"
services:
  termit-nginx:
    build:
      context: nginx
      args:
        CONTEXT: ${ROOT}
    image: termit-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - termit
      - termit-server
      - termit-db-server
  termit-db-server:
    build:
      context: db-server
      args:
        GRAPHDB_ZIP: graphdb-free-9.6.0-dist.zip
    image: termit-db-server
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.external-url=${URL}${ROOT}/sluzby/db-server
    restart: always
    ports:
      - "7200:7200"
    volumes:
      - termit-db-server:/graphdb/home
  termit-server:
    depends_on:
      - termit-db-server
    image: termit-server
    environment:
      REPOSITORY_URL: http://termit-db-server:7200/repositories/termit
      REPOSITORY_PUBLICURL: ${URL}${ROOT}/sluzby/db-server/repositories/termit
      SERVER_SERVLET_CONTEXT-PATH: ${ROOT}/sluzby/server
      FILE_STORAGE: /tmp/storage
      TEXTANALYSIS_URL: https://localhost/annotate?enableKeywordExtraction=true # TODO parameterize
    ports:
      - "8080:8080"
    volumes:
      - termit-server:/tmp
  termit:
    depends_on:
      - termit-server
    image: termit
    environment:
      REACT_APP_SERVER_URL: ${URL}${ROOT}/sluzby/server
      SERVER_URL: ${URL}${ROOT}/sluzby/server
    ports:
      - "3000:80"
volumes:
  termit-db-server:
  termit-server:
